
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Program Files/Git/mingw64/bin/"
      - "C:/Program Files/Git/mingw64/sbin/"
      - "C:/Program Files/Git/mingw64/"
      - "C:/Users/JBlen/bin/"
      - "C:/Program Files/Git/mingw64/bin/"
      - "C:/Program Files/Git/usr/local/bin/"
      - "C:/Program Files/Git/usr/bin/"
      - "C:/Program Files (x86)/Embarcadero/Studio/23.0/bin/"
      - "C:/Users/Public/Documents/Embarcadero/Studio/23.0/BPL/"
      - "C:/Program Files (x86)/Embarcadero/Studio/23.0/bin64/"
      - "C:/Users/Public/Documents/Embarcadero/Studio/23.0/BPL/Win64/"
      - "C:/Embarcadero/Studio/21.0/bin/"
      - "C:/Embarcadero/Studio/21.0/bin64/"
      - "C:/Program Files (x86)/Embarcadero/Studio/21.0/bin/"
      - "C:/Users/Public/Documents/Embarcadero/Studio/21.0/Bpl/"
      - "C:/Program Files (x86)/Embarcadero/Studio/21.0/bin64/"
      - "C:/Users/Public/Documents/Embarcadero/Studio/21.0/Bpl/Win64/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Program Files/Intel/WiFi/bin/"
      - "C:/Program Files/Common Files/Intel/WirelessCommon/"
      - "C:/Program Files (x86)/Skype/Phone/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/ProgramsInstalled/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/TortoiseSVN/bin/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/nodejs/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Users/JBlen/.local/bin/"
      - "C:/Users/JBlen/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/JBlen/.lmstudio/bin/"
      - "C:/Users/JBlen/AppData/Local/Programs/Ollama/"
      - "C:/Users/JBlen/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/JBlen/AppData/Roaming/npm/"
      - "C:/Program Files/Git/usr/bin/vendor_perl/"
      - "C:/Program Files/Git/usr/bin/core_perl/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Program Files/Git/mingw64/bin/mingw32-make.exe.com"
      - "C:/Program Files/Git/mingw64/bin/mingw32-make.exe"
      - "C:/Program Files/Git/mingw64/sbin/mingw32-make.exe.com"
      - "C:/Program Files/Git/mingw64/sbin/mingw32-make.exe"
      - "C:/Program Files/Git/mingw64/mingw32-make.exe.com"
      - "C:/Program Files/Git/mingw64/mingw32-make.exe"
      - "C:/Users/JBlen/bin/mingw32-make.exe.com"
      - "C:/Users/JBlen/bin/mingw32-make.exe"
      - "C:/Program Files/Git/mingw64/bin/mingw32-make.exe.com"
      - "C:/Program Files/Git/mingw64/bin/mingw32-make.exe"
      - "C:/Program Files/Git/usr/local/bin/mingw32-make.exe.com"
      - "C:/Program Files/Git/usr/local/bin/mingw32-make.exe"
      - "C:/Program Files/Git/usr/bin/mingw32-make.exe.com"
      - "C:/Program Files/Git/usr/bin/mingw32-make.exe"
      - "C:/Program Files (x86)/Embarcadero/Studio/23.0/bin/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Embarcadero/Studio/23.0/bin/mingw32-make.exe"
      - "C:/Users/Public/Documents/Embarcadero/Studio/23.0/BPL/mingw32-make.exe.com"
      - "C:/Users/Public/Documents/Embarcadero/Studio/23.0/BPL/mingw32-make.exe"
      - "C:/Program Files (x86)/Embarcadero/Studio/23.0/bin64/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Embarcadero/Studio/23.0/bin64/mingw32-make.exe"
      - "C:/Users/Public/Documents/Embarcadero/Studio/23.0/BPL/Win64/mingw32-make.exe.com"
      - "C:/Users/Public/Documents/Embarcadero/Studio/23.0/BPL/Win64/mingw32-make.exe"
      - "C:/Embarcadero/Studio/21.0/bin/mingw32-make.exe.com"
      - "C:/Embarcadero/Studio/21.0/bin/mingw32-make.exe"
      - "C:/Embarcadero/Studio/21.0/bin64/mingw32-make.exe.com"
      - "C:/Embarcadero/Studio/21.0/bin64/mingw32-make.exe"
      - "C:/Program Files (x86)/Embarcadero/Studio/21.0/bin/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Embarcadero/Studio/21.0/bin/mingw32-make.exe"
      - "C:/Users/Public/Documents/Embarcadero/Studio/21.0/Bpl/mingw32-make.exe.com"
      - "C:/Users/Public/Documents/Embarcadero/Studio/21.0/Bpl/mingw32-make.exe"
      - "C:/Program Files (x86)/Embarcadero/Studio/21.0/bin64/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Embarcadero/Studio/21.0/bin64/mingw32-make.exe"
      - "C:/Users/Public/Documents/Embarcadero/Studio/21.0/Bpl/Win64/mingw32-make.exe.com"
      - "C:/Users/Public/Documents/Embarcadero/Studio/21.0/Bpl/Win64/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Program Files/Intel/WiFi/bin/mingw32-make.exe.com"
      - "C:/Program Files/Intel/WiFi/bin/mingw32-make.exe"
      - "C:/Program Files/Common Files/Intel/WirelessCommon/mingw32-make.exe.com"
      - "C:/Program Files/Common Files/Intel/WirelessCommon/mingw32-make.exe"
      - "C:/Program Files (x86)/Skype/Phone/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Skype/Phone/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/ProgramsInstalled/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe.com"
      - "C:/ProgramsInstalled/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe"
      - "C:/Program Files/TortoiseSVN/bin/mingw32-make.exe.com"
      - "C:/Program Files/TortoiseSVN/bin/mingw32-make.exe"
      - "C:/Program Files/Git/cmd/mingw32-make.exe.com"
      - "C:/Program Files/Git/cmd/mingw32-make.exe"
      - "C:/Program Files/nodejs/mingw32-make.exe.com"
      - "C:/Program Files/nodejs/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "C:/Users/JBlen/.local/bin/mingw32-make.exe.com"
      - "C:/Users/JBlen/.local/bin/mingw32-make.exe"
      - "C:/Users/JBlen/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/JBlen/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/JBlen/.lmstudio/bin/mingw32-make.exe.com"
      - "C:/Users/JBlen/.lmstudio/bin/mingw32-make.exe"
      - "C:/Users/JBlen/AppData/Local/Programs/Ollama/mingw32-make.exe.com"
      - "C:/Users/JBlen/AppData/Local/Programs/Ollama/mingw32-make.exe"
      - "C:/Users/JBlen/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "C:/Users/JBlen/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe"
      - "C:/Users/JBlen/AppData/Roaming/npm/mingw32-make.exe.com"
      - "C:/Users/JBlen/AppData/Roaming/npm/mingw32-make.exe"
      - "C:/Program Files/Git/usr/bin/vendor_perl/mingw32-make.exe.com"
      - "C:/Program Files/Git/usr/bin/vendor_perl/mingw32-make.exe"
      - "C:/Program Files/Git/usr/bin/core_perl/mingw32-make.exe.com"
      - "C:/Program Files/Git/usr/bin/core_perl/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      CMAKE_PREFIX_PATH:
        - "C:/Program Files/Git/mingw64"
      ENV{PATH}:
        - "C:\\Users\\JBlen\\bin"
        - "C:\\Program Files\\Git\\mingw64\\bin"
        - "C:\\Program Files\\Git\\usr\\local\\bin"
        - "C:\\Program Files\\Git\\usr\\bin"
        - "C:\\Program Files\\Git\\usr\\bin"
        - "C:\\Program Files\\Git\\mingw64\\bin"
        - "C:\\Program Files\\Git\\usr\\bin"
        - "C:\\Users\\JBlen\\bin"
        - "C:\\Program Files (x86)\\Embarcadero\\Studio\\23.0\\bin"
        - "C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\23.0\\Bpl"
        - "C:\\Program Files (x86)\\Embarcadero\\Studio\\23.0\\bin64"
        - "C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\23.0\\Bpl\\Win64"
        - "C:\\Embarcadero\\Studio\\21.0\\bin"
        - "C:\\Embarcadero\\Studio\\21.0\\bin64"
        - "C:\\Program Files (x86)\\Embarcadero\\Studio\\21.0\\bin"
        - "C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\21.0\\Bpl"
        - "C:\\Program Files (x86)\\Embarcadero\\Studio\\21.0\\bin64"
        - "C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\21.0\\Bpl\\Win64"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0"
        - "C:\\Program Files\\Intel\\WiFi\\bin"
        - "C:\\Program Files\\Common Files\\Intel\\WirelessCommon"
        - "C:\\Program Files (x86)\\Skype\\Phone"
        - "C:\\WINDOWS\\System32\\OpenSSH"
        - "C:\\ProgramsInstalled\\Windows Kits\\10\\Windows Performance Toolkit"
        - "C:\\Program Files\\TortoiseSVN\\bin"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\nodejs"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Users\\JBlen\\.local\\bin"
        - "C:\\Users\\JBlen\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\JBlen\\.lmstudio\\bin"
        - "C:\\Users\\JBlen\\AppData\\Local\\Programs\\Ollama"
        - "C:\\Users\\JBlen\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\JBlen\\AppData\\Roaming\\npm"
        - "C:\\Program Files\\Git\\usr\\bin\\vendor_perl"
        - "C:\\Program Files\\Git\\usr\\bin\\core_perl"
...
